<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.13.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
		<PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NUnit" Version="4.3.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.4.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="Selenium.Support" Version="4.27.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.27.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="143.0.7499.4000" />
		<PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="140.0.3485.66" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Selenium.BaseComponents\Selenium.BaseComponents.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
